[package]
name = "standalone-test"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.22", features = ["derive"] }
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
